<h1 align="center">Assignment - 1</h1>
<br><br>


<h3 align = "left">
Abhishek Vohra <br></h3>




### Q1 (a)

In [1]:
import numpy as np

arr = np.array([1,2,3,6,4,5])
newArray = np.flipud(arr)

print("Reversed Array : ",newArray)



Reversed Array :  [5 4 6 3 2 1]


### Q1 (b)

In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method - 1 (using flatten method)
# Row Major Flattening
array2 = array1.flatten('C')
print(array2)

# Column Major Flattening
array3 = array1.flatten('F')
print(array3)


# Method - 2 (using reshape method)
array4 = array1.reshape(-1)
print(array4)



### Q1 (c)

In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"Array 1 = {arr1}")
print(f"Array 2 = {arr2}")

# is greater comparison
print("arr1 > arr2")
print(np.greater(arr1,arr2))

# is greater than equal to comparison
print("arr1 >= arr2")
print(np.greater_equal(arr1,arr2))

# is less than comparison
print("arr1 < arr2")
print(np.less(arr1,arr2))

# is less than equal to comparison
print("arr1 <= arr2")
print(np.less_equal(arr1,arr2))

# is equal to comparison
print("arr1 = arr2")
print(np.equal(arr1,arr2))


# another method to check equality
if (np.array_equal(arr1,arr2)):
    print("arr1 == arr2")

else:
    print("They are not equal")





Array 1 = [[1 2]
 [3 4]]
Array 2 = [[1 2]
 [3 4]]
arr1 > arr2
[[False False]
 [False False]]
arr1 >= arr2
[[ True  True]
 [ True  True]]
arr1 < arr2
[[False False]
 [False False]]
arr1 <= arr2
[[ True  True]
 [ True  True]]
arr1 = arr2
[[ True  True]
 [ True  True]]
arr1 == arr2


### Q1 (d)

In [4]:
import numpy as np

# i
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Most frequently occuring element is = ", np.bincount(x).argmax());

# ii
y = np.array([1,1,1,2,3,4,2,4,3,3])
print("Most frequently occuring element is = ", np.bincount(y).argmax());


Most frequently occuring element is =  1
Most frequently occuring element is =  1


### Q1 (e)

In [5]:
import numpy as np

gfg = np.matrix('[4,1,9; 12,3,1; 4,5,6]')

# (i) Sum Of all Elements
print("Sum of all elements of matrix = ", gfg.sum())

# (ii) Sum of all Elements Row-wise
print("Sum of all Elements Row-wise = ", gfg.sum(axis=1))

# (iii) Sum of all Elements Column-wise
print("Sum of all Elements Columns-wise = ", gfg.sum(axis=0))

Sum of all elements of matrix =  45
Sum of all Elements Row-wise =  [[14]
 [16]
 [15]]
Sum of all Elements Columns-wise =  [[20  9 16]]


### Q1 (f)

In [6]:
import numpy as np

n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])

# (i) Sum of diagonal elements
print("Sum of diagonal elements of the Matrix = ", np.trace(n_array))

a, b = np.linalg.eig(n_array)
# (ii) Eigen values of matrix
print("Eigen Values of the Matrix are = ", a)

# (iii) Eigen Vectors of the Matrix
print("Eigen Vectors of the Matrix are = ", b)

# (iv) Inverse of the matrix
print("Inverse of Matrix = ", np.linalg.inv(n_array))

# (v) Determinant of the matrix
print("Determinant of matrix = ", np.linalg.det(n_array))

Sum of diagonal elements of the Matrix =  176
Eigen Values of the Matrix are =  [98.16835147 28.097044   49.73460452]
Eigen Vectors of the Matrix are =  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of Matrix =  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix =  137180.0000000001


### Q1 (g)

In [7]:
import numpy as np

# (i)

p = [[1,2],[2,3]]
q = [[4,5],[6,7]]

print("Product of the two matrices = ", np.matmul(p,q))

print("Covariance between the two matrices = ", np.cov(p,q))


# (ii)

p1 = [[1,2],[2,3],[4,5]]
q1 = [[4,5,1],[6,7,2]]

print("Product of the two matrices = ", np.matmul(p1,q1))
# the line below produces error
# because covariance can be calculate for matrices of same dimensions only
# print("Covariance between the two matrices = ", np.cov(p1,q1))


Product of the two matrices =  [[16 19]
 [26 31]]
Covariance between the two matrices =  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Product of the two matrices =  [[16 19  5]
 [26 31  8]
 [46 55 14]]


### Q1 (h)

In [8]:
import numpy as np

x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])

# Inner Product
print("Inner Product = ", np.inner(x,y))

# Outer Product
print("Outer Product = ", np.outer(x,y))

# Cartesian Product
print("Cartesian Product = ", np.cross(x,y))

Inner Product =  [[17 52]
 [13 62]]
Outer Product =  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product =  [[-20   4   7]
 [-84  36  20]]


### Q2 (a)

In [9]:
import numpy as np

array1 = np.array([[1,-2,3],[-4,5,-6]])

# (i) element wise absolute value
print("Element wise absolute value = ", np.absolute(array1))

# (ii) Percentile
np.ndarray.flatten(array1)


print("25th percentile along every row : ", np.percentile(array1, 25, axis=1))
print("25th percentile along every column : ", np.percentile(array1, 25, axis=0))


print("50th percentile along every row : ", np.percentile(array1, 50, axis=1))
print("50th percentile along every column : ", np.percentile(array1, 50, axis=0))


print("75th percentile along every row : ", np.percentile(array1, 75, axis=1))
print("75th percentile along every column : ", np.percentile(array1, 75, axis=0))


# (iii) Mean Median Mode

print("Mean of each Column : ", np.mean(array1,axis=0))
print("Mean of each Row : ", np.mean(array1,axis=0))

print("Median of each Column : ", np.median(array1,axis=0))
print("Median of each Row : ", np.median(array1,axis=0))

print("Standard Deviation of each Column : ", np.std(array1,axis=0))
print("Standard Deviation of each Row : ", np.std(array1,axis=0))

Element wise absolute value =  [[1 2 3]
 [4 5 6]]
25th percentile along every row :  [-0.5 -5. ]
25th percentile along every column :  [-2.75 -0.25 -3.75]
50th percentile along every row :  [ 1. -4.]
50th percentile along every column :  [-1.5  1.5 -1.5]
75th percentile along every row :  [2.  0.5]
75th percentile along every column :  [-0.25  3.25  0.75]
Mean of each Column :  [-1.5  1.5 -1.5]
Mean of each Row :  [-1.5  1.5 -1.5]
Median of each Column :  [-1.5  1.5 -1.5]
Median of each Row :  [-1.5  1.5 -1.5]
Standard Deviation of each Column :  [2.5 3.5 4.5]
Standard Deviation of each Row :  [2.5 3.5 4.5]


### Q2 (b)

In [10]:
import numpy as np

a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])

# floor
print ("Floor : ", np.floor(a))

# ceiling
print ("Ceiling : ", np.ceil(a))

# truncated value
print ("Truncated Values : ", np.trunc(a))

# Rounded values
print ("Rounded Values : ", np.round(a))

Floor :  [-2. -2. -1.  0.  1.  1.  3.]
Ceiling :  [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values :  [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values :  [-2. -2. -0.  0.  2.  2.  3.]


### Q3 (a)

In [11]:
import numpy as np

a = np.array([10,52,62,16,16,54,453])

# (i) sorted array
print ("Sorted array : ", np.sort(a))

# (ii) indices of sorted array
print ("Indices of sorted array : ", np.argsort(a))

# (iii) 4 smallest elements
a = np.sort(a)
print ("4 smallest elements : ", a[:4])

# (iv) 5 largest elements
print ("5 largest elements : ", a[-5:])

Sorted array :  [ 10  16  16  52  54  62 453]
Indices of sorted array :  [0 3 4 1 5 2 6]
4 smallest elements :  [10 16 16 52]
5 largest elements :  [ 16  52  54  62 453]


### Q3 (b)

In [ ]:
from unicodedata import decimal
import numpy as np

a = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# (i) integer elements only 
result1 = a[a == a.astype(int)]
print ("Integer Elements only : ", result1)

# (ii) float elements only
print ("Float Elements only : ", a[a != a.astype(int)])

### Q4 (a)

In [16]:
from distutils import text_file
import numpy as np
from PIL import Image

def write_pixel(t, handle):
    handle.write("%d, "%t)

def write_pixel_col(t, handle):
    handle.write("%d %d, "%(t[0],t[1]))


def img_to_array(path,chroma):
    text_file_handle = open("out.txt","w")

    im = Image.open(path)

    width, height = im.size

    for column in range(0,width):
        for row in range(0,height):
            if (chroma == 1):
                write_pixel(im.getpixel((column,row)), text_file_handle)
            else:
                write_pixel_col(im.getpixel((column,row)), text_file_handle)
            text_file_handle.write("\n")
        
    print ("Data Successfully updated")
    text_file_handle.close()


path = "gray.jpg"
chroma = int(input("Enter 1 if image is grayscale. Otherwise Enter 2 : "))

img_to_array(path,chroma)



Enter 1 if image is grayscale. Otherwise Enter 2 : 1
Data Successfully updated


### Q4 (b)


The ouput file is loaded in the jupyter notebook. Its in the same directory as the jupyter notebook